# Data Understanding
This notebook loads the e-commerce dataset and inspects its structure, data types, summary statistics, missing values, and duplicate records.

In [13]:
# Load pandas for data manipulation.
import pandas as pd

# Set option to display all columns and format float values to two decimal places (to avoid scientific notation).
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)

In [14]:
# Read the raw e-commerce dataset from the project dataset folder.
ecommerce_df = pd.read_csv(r'dataset/raw/ecommerce_dataset_+1m.csv')

In [15]:
# DIsplay a random sample of 10 rows from the dataset to get an overview of the data.
ecommerce_df.sample(10)

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,return_reason,customer_id,customer_name,gender,age,customer_segment,country,city,customer_loyalty_score,total_orders_by_customer,account_creation_date,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,currency,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,rating,review_sentiment,customer_feedback,coupon_used,coupon_code,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
762668,ORD-18764,2024-05-04 12:13:15.460829,2024,5,4,12,13,15,Yes,Completed,NaN,CUS-J50W7,Daniel Phelps,Male,41,Regular,Belgium,Brussels,50.50,45,2021-09-17,PRD-FFFJ,Sports Bra High Impact,Clothing,Kids Wear,Canon,3.80,205,498,39.53,2,0,0.00,79.06,34.08,44.98,6.82,USD,Credit Card,Paid,No,Express,17.31,4,Belgium,EU-Central,Delivered,2,Negative,Excellent!,No,NaN,Google Ads,Mobile,Referral,52.30,20,Yes,74.70,56.89,High,Yes
657540,ORD-BBHES,2025-03-27 08:20:05.889876,2025,3,27,8,20,5,No,Cancelled,NaN,CUS-HFAP0,Amber Thompson,Female,60,Regular,United States,Chicago,11.00,20,2025-02-26,PRD-7B6X,Air Fryer 5L,Home,Appliances,JBL,4.00,2382,424,186.38,2,15,55.91,316.85,258.32,58.53,25.58,USD,Apple Pay,Pending,Yes,Next Day,10.33,14,United States,EU-Central,Delivered,2,Negative,NaN,Yes,CPN-O7F,Instagram,Mobile,Direct,6.70,14,Yes,6.30,18.47,High,Yes
318384,ORD-8ZYAE,2025-12-12 19:35:08.230580,2025,12,12,19,35,8,No,Completed,NaN,CUS-DMTHW,Brian Snyder,Male,75,Regular,United Kingdom,Manchester,5.30,6,2023-05-12,PRD-2FJW,Vacuum Robot Cleaner,Home,Bedding,Logitech,3.70,73,690,202.49,4,10,81.00,728.96,394.32,334.64,48.85,USD,Apple Pay,Paid,Yes,Standard,23.68,2,United Kingdom,USA-West,Delivered,1,Negative,Good value for money,No,NaN,Email,Tablet,Email,33.60,16,No,31.20,45.91,Medium,Yes
578083,ORD-KU3KY,2025-03-20 20:14:13.763168,2025,3,20,20,14,13,No,Completed,NaN,CUS-MHFTA,Melissa Sparks,Female,41,Premium,United Kingdom,Glasgow,59.20,46,2025-03-06,PRD-NRUK,Wireless Bluetooth Earbuds,Electronics,Smartphones,Fitbit,3.30,1392,689,161.48,5,5,40.37,767.03,439.20,327.83,74.25,USD,Bank Transfer,Paid,No,Standard,8.65,8,United Kingdom,Asia-Pacific,Delivered,1,Negative,Good value for money,No,NaN,Google Ads,Mobile,Social,56.90,12,Yes,61.50,42.74,Medium,Yes
124368,ORD-EVQFQ,2025-08-14 00:17:15.615177,2025,8,14,0,17,15,No,Completed,NaN,CUS-8OPA5,Janice Rodriguez,Female,59,Premium,United Kingdom,Glasgow,83.30,27,2022-11-20,PRD-G0AN,Exercise Ball,Sports,Accessories,Dell,3.30,1947,979,72.73,1,10,7.27,65.46,46.77,18.69,3.50,USD,Bank Transfer,Paid,No,Next Day,5.15,13,United Kingdom,USA-East,Delivered,4,Positive,NaN,Yes,CPN-IG8,Facebook,Tablet,Search,2.80,4,No,42.70,28.55,Medium,No
880234,ORD-Z0LLN,2025-07-21 20:36:11.576930,2025,7,21,20,36,11,No,Returned,Not As Described,CUS-E15HW,Mary Valentine,Female,30,Regular,Italy,Florence,96.40,15,2022-03-10,PRD-PEV7,Badminton Racket,Sports,Sports Wear,Fitbit,5.00,1803,629,223.80,3,0,0.00,671.40,458.43,212.97,61.07,USD,PayPal,Paid,No,Next Day,20.37,12,Italy,EU-Central,In Transit,2,Negative,Not satisfied,No,NaN,Instagram,Desktop,Social,25.30,2,Yes,24.80,31.72,High,Yes
210038,ORD-M0WVL,2025-03-14 15:40:14.940629,2025,3,14,15,40,14,No,Returned,Defective Product,CUS-05CZQ,Trevor Washington,Male,37,Premium,Germany,Hamburg,55.60,18,2022-06-04,PRD-XSR0,Foam Roller,Health,Medical Devices,Asus,4.40,4383,52,198.14,1,10,19.81,178.33,110.26,68.07,11.03,USD,PayPal,Paid,Yes,Next Day,2.17,14,Germany,UK,In Transit,5,Positive,Average quality,Yes,CPN-MCB,Google Ads,Mobile,Email,34.20,17,Yes,3.50,38.17,High,Yes
991433,ORD-JMG93,2024-12-04 09:11:14.263086,2024,12,4,9,11,14,No,Completed,NaN,CUS-KKWH5,Zachary Patel,Male,25,Premium,Netherlands,Eindhoven,57.60,22,2024-02-08,PRD-P4ZY,Water Bottle Insulated,Sports,Gym Equipment,Anker,3.60,2772,337,103.20,1,0,0.00,103.20,52.13,51.07,8.73,USD,Apple Pay,Paid,No,Next Day,24.03,4,Netherlands,EU-Central,Delivered,5,Positive,Highly recommended,No,NaN,Instagram,Desktop,Search,42.90,17,Yes,55.90,49.49,Low,Yes
535325,ORD-UFGKP,2024-04-23 12:18:27.067753,2024,4,23,12,18,27,No,Cancelled,NaN,CUS-5W2RI,Nicole Morrison MD,Female,75,Premium,Belgium,Antwerp,73.00,39,2021-07-16,PRD-8KQE,Yoga Pants Leggings,Clothing,Accessories,JBL,3.60,4118,739,22.20,4,5,4.44,84.36,57.40,26.96,8.30,USD,Apple Pay,Failed,No,Express,0.96,9,Belgium,EU-Central,In Transit,3,Neutral,Fast delivery,No,NaN,Affiliate,Tablet,Search,44.20,14,Yes,42.40,31.96,Medium,No
836855,ORD-6AG43,2024-08-14 05:56:21.359064,2024,8,14,5,56,21,No,Completed,NaN,CUS-5PHEI,Victor Sloan,Male,28,Premium,Italy,Florence,40.50,29,2022-01-01,PRD-UOG7,Massage Gun Deep Tissue,Health,Fitness,Fitbit,3.30,4718,936,69.38,3,5,10.41,197.73,87.57,110.16,12.55,USD,PayPal,Paid,No,Economy,21.00,7,Italy,USA-West,In Transit,4,Positive,Great product!,Yes,CPN-BNX,Email,Desktop,Social,12.10,8,No,60.10,55.71,Medium,Yes

In [16]:
# Check the overall dataset dimensions: rows and columns.
ecommerce_df.shape

(1000123, 62)

In [17]:
# Print a concise summary of column types and non-null counts.
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 62 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  object
 1   order_date                1000123 non-null  object
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  object
 9   order_status              1000123 non-null  object
 10  return_reason             99879 non-null    object
 11  customer_id               1000123 non-null  object
 12  customer_name             1000123 non-null  object
 13  gender                    1000123 non-null  object
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  object
 16  country                   1000123 non-null  object
 17  city                      1000123 non-null  object
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  object
 21  product_id                1000123 non-null  object
 22  product_name              1000123 non-null  object
 23  category                  1000123 non-null  object
 24  sub_category              1000123 non-null  object
 25  brand                     1000123 non-null  object
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  object
 38  payment_method            1000123 non-null  object
 39  payment_status            1000123 non-null  object
 40  installment_plan          1000123 non-null  object
 41  shipping_method           1000123 non-null  object
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  object
 45  warehouse_location        1000123 non-null  object
 46  delivery_status           1000123 non-null  object
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  object
 49  customer_feedback         800506 non-null   object
 50  coupon_used               1000123 non-null  object
 51  coupon_code               500040 non-null   object
 52  campaign_source           1000123 non-null  object
 53  device_type               1000123 non-null  object
 54  traffic_source            1000123 non-null  object
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  object
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  object
 61  support_ticket_created    1000123 non-null  object
dtypes: float64(12), int64(15), object(35)
memory usage: 473.1+ MB

In [18]:
# Compute descriptive statistics
ecommerce_df.describe()

,order_year,order_month,order_day,order_hour,order_minute,order_second,age,customer_loyalty_score,total_orders_by_customer,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,shipping_cost_usd,delivery_days,rating,session_duration_minutes,pages_visited,fraud_risk_score,profit_margin_percent
count,"1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00"
mean,"2,024.59",6.51,15.75,11.49,29.49,29.49,46.49,49.97,25.49,4.00,"2,501.57",499.81,147.02,3.00,8.50,37.48,403.24,242.31,160.93,30.25,12.50,7.51,3.00,30.51,10.51,49.96,39.47
std,0.58,3.45,8.80,6.92,17.31,17.33,16.73,28.89,14.43,0.58,"1,443.46",288.86,103.67,1.41,7.60,56.78,370.13,226.72,161.93,28.89,7.22,4.03,1.41,17.03,5.77,28.85,10.94
min,"2,024.00",1.00,1.00,0.00,0.00,0.00,18.00,0.00,1.00,3.00,0.00,0.00,10.00,1.00,0.00,0.00,7.53,4.03,0.70,0.43,0.00,1.00,1.00,1.00,1.00,0.00,6.66
25%,"2,024.00",4.00,8.00,5.00,14.00,14.00,32.00,24.90,13.00,3.50,"1,253.00",250.00,69.51,2.00,0.00,0.00,139.02,82.45,50.69,10.12,6.26,4.00,2.00,15.70,6.00,25.00,31.69
50%,"2,025.00",7.00,16.00,11.00,30.00,29.00,46.00,50.00,25.00,4.00,"2,503.00",500.00,125.11,3.00,10.00,16.91,290.19,172.53,108.79,21.28,12.50,8.00,3.00,30.50,11.00,50.00,39.90
75%,"2,025.00",10.00,23.00,17.00,44.00,44.00,61.00,75.00,38.00,4.50,"3,752.00",750.00,195.61,4.00,15.00,49.26,545.76,326.45,214.64,40.59,18.74,11.00,4.00,45.30,16.00,74.90,48.17
max,"2,026.00",12.00,31.00,23.00,59.00,59.00,75.00,100.00,50.00,5.00,"5,000.00","1,000.00",500.00,5.00,25.00,624.71,"2,499.75","1,743.70","1,495.75",245.59,25.00,14.00,5.00,60.00,20.00,100.00,60.02

In [23]:
# Get the percentage of missing values for each column in the dataset.
print((ecommerce_df.isnull().sum() / ecommerce_df.shape[0] * 100).to_string())

order_id                    0.00
order_date                  0.00
order_year                  0.00
order_month                 0.00
order_day                   0.00
order_hour                  0.00
order_minute                0.00
order_second                0.00
is_weekend                  0.00
order_status                0.00
return_reason              90.01
customer_id                 0.00
customer_name               0.00
gender                      0.00
age                         0.00
customer_segment            0.00
country                     0.00
city                        0.00
customer_loyalty_score      0.00
total_orders_by_customer    0.00
account_creation_date       0.00
product_id                  0.00
product_name                0.00
category                    0.00
sub_category                0.00
brand                       0.00
product_rating_avg          0.00
product_reviews_count       0.00
stock_quantity              0.00
unit_price_usd              0.00
quantity                    0.00
discount_percent            0.00
discount_amount_usd         0.00
total_price_usd             0.00
cost_usd                    0.00
profit_usd                  0.00
tax_usd                     0.00
currency                    0.00
payment_method              0.00
payment_status              0.00
installment_plan            0.00
shipping_method             0.00
shipping_cost_usd           0.00
delivery_days               0.00
shipping_country            0.00
warehouse_location          0.00
delivery_status             0.00
rating                      0.00
review_sentiment            0.00
customer_feedback          19.96
coupon_used                 0.00
coupon_code                50.00
campaign_source             0.00
device_type                 0.00
traffic_source              0.00
session_duration_minutes    0.00
pages_visited               0.00
abandoned_cart_before       0.00
fraud_risk_score            0.00
profit_margin_percent       0.00
order_priority              0.00
support_ticket_created      0.00

Notable missing values were observed in **``return_season``**, **``customer_feedback``**, and **``coupon_code``**.

In [20]:
# Total of duplicate rows
duplicates_row = ecommerce_df.duplicated().sum()
print(f'Total of Duplicate Rows : {duplicates_row}')

Total of Duplicate Rows : 0

In [21]:
"""
    Determine if any column in the dataset has unique values, which can be used as a unique identifier for each row. 
    True = unique identifier candidate
"""
print(ecommerce_df.apply(lambda col: col.is_unique).to_string())

order_id                    False
order_date                   True
order_year                  False
order_month                 False
order_day                   False
order_hour                  False
order_minute                False
order_second                False
is_weekend                  False
order_status                False
return_reason               False
customer_id                 False
customer_name               False
gender                      False
age                         False
customer_segment            False
country                     False
city                        False
customer_loyalty_score      False
total_orders_by_customer    False
account_creation_date       False
product_id                  False
product_name                False
category                    False
sub_category                False
brand                       False
product_rating_avg          False
product_reviews_count       False
stock_quantity              False
unit_price_usd              False
quantity                    False
discount_percent            False
discount_amount_usd         False
total_price_usd             False
cost_usd                    False
profit_usd                  False
tax_usd                     False
currency                    False
payment_method              False
payment_status              False
installment_plan            False
shipping_method             False
shipping_cost_usd           False
delivery_days               False
shipping_country            False
warehouse_location          False
delivery_status             False
rating                      False
review_sentiment            False
customer_feedback           False
coupon_used                 False
coupon_code                 False
campaign_source             False
device_type                 False
traffic_source              False
session_duration_minutes    False
pages_visited               False
abandoned_cart_before       False
fraud_risk_score            False
profit_margin_percent       False
order_priority              False
support_ticket_created      False

>Based on the data, it appears that the dataset does not have a suitable unique identifier column. Although order_date contains unique values, it is not a reliable unique identifier since it is a timestamp and may not remain unique in real-world scenarios.