# Data Understanding
This notebook loads the e-commerce dataset and inspects its structure, data types, summary statistics, missing values, and duplicate records.

In [2]:
# Load pandas for data manipulation.
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)

In [3]:
# Read the raw e-commerce dataset from the project dataset folder.
ecommerce_df = pd.read_csv(r'dataset/raw/ecommerce_dataset_+1m.csv')

In [11]:
# DIsplay a random sample of 10 rows from the dataset to get an overview of the data.
ecommerce_df.sample(10)

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,return_reason,customer_id,customer_name,gender,age,customer_segment,country,city,customer_loyalty_score,total_orders_by_customer,account_creation_date,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,currency,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,rating,review_sentiment,customer_feedback,coupon_used,coupon_code,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
570875,ORD-UNX3A,2025-01-31 03:38:32.128268,2025,1,31,3,38,32,No,Completed,NaN,CUS-O9WI9,Sean Kennedy,Male,54,Regular,Spain,Valencia,38.40,1,2024-08-22,PRD-58PD,Yoga Mat Non-Slip,Health,Personal Care,Dell,4.60,509,420,86.38,4,15,51.83,293.69,164.72,128.97,17.87,USD,Debit Card,Paid,No,Express,6.42,10,Spain,Asia-Pacific,Delivered,3,Neutral,Highly recommended,No,NaN,Facebook,Desktop,Search,50.90,6,Yes,52.40,43.91,High,No
98550,ORD-SQJMD,2024-08-22 08:15:38.037277,2024,8,22,8,15,38,No,Completed,NaN,CUS-81P6Y,Tiffany Hayes,Female,45,Regular,Canada,Calgary,10.70,47,2022-05-19,PRD-XP7L,Bedsheet Set Cotton,Home,Bedding,Lenovo,4.00,3228,15,186.12,2,15,55.84,316.40,192.24,124.16,22.94,USD,Credit Card,Paid,Yes,Express,12.16,10,Canada,USA-West,Delivered,4,Positive,Excellent!,No,NaN,Organic,Desktop,Email,29.90,9,Yes,33.20,39.24,Medium,No
795662,ORD-FATG5,2025-04-29 19:55:05.699651,2025,4,29,19,55,5,No,Cancelled,NaN,CUS-B8CJI,Ms. Rachel Ford,Female,44,Regular,Netherlands,Amsterdam,10.90,40,2022-09-15,PRD-W9NS,Denim Jeans Slim Fit,Clothing,Kids Wear,Huawei,4.60,53,944,21.68,2,10,4.34,39.02,20.88,18.14,3.48,USD,Bank Transfer,Paid,No,Economy,20.33,11,Netherlands,USA-East,Delivered,1,Negative,Could be better,No,NaN,Affiliate,Mobile,Social,40.40,20,No,8.00,46.49,Low,Yes
152835,ORD-46KYZ,2025-07-29 03:03:07.188344,2025,7,29,3,3,7,No,Pending,NaN,CUS-WAPS5,Kimberly Parker,Female,68,VIP,Belgium,Liege,96.40,44,2021-12-28,PRD-K6BL,Yoga Mat Non-Slip,Health,Personal Care,Canon,3.50,4058,329,43.46,1,5,2.17,41.29,18.38,22.91,2.14,USD,Credit Card,Pending,No,Standard,19.34,6,Belgium,Asia-Pacific,Delivered,3,Neutral,Fast delivery,Yes,CPN-BN1,Instagram,Tablet,Search,7.80,10,Yes,82.20,55.49,Medium,No
761515,ORD-HCDSL,2024-08-30 08:31:31.817322,2024,8,30,8,31,31,No,Completed,NaN,CUS-TQCOR,Robert Villa,Male,45,VIP,Germany,Frankfurt,46.80,46,2022-08-18,PRD-E021,Cotton T-Shirt Pack,Clothing,Accessories,Anker,3.60,3154,306,77.23,5,10,38.62,347.53,214.95,132.58,28.57,USD,Bank Transfer,Paid,No,Standard,22.03,2,Germany,USA-East,In Transit,2,Negative,NaN,No,NaN,Instagram,Tablet,Social,52.40,20,Yes,27.80,38.15,High,Yes
843904,ORD-G47RV,2024-05-05 05:34:45.998926,2024,5,5,5,34,45,Yes,Completed,NaN,CUS-68VG9,Mason Martinez,Male,55,Regular,Germany,Hamburg,70.10,17,2021-04-01,PRD-B5XD,Running Shoes Air Zoom,Clothing,Accessories,Xiaomi,3.80,2128,635,102.02,3,10,30.61,275.45,161.55,113.90,14.21,USD,Credit Card,Paid,Yes,Next Day,10.62,8,Germany,Asia-Pacific,Delivered,1,Negative,Good value for money,No,NaN,Affiliate,Desktop,Search,46.70,3,No,11.60,41.35,Medium,Yes
114646,ORD-2UTVO,2025-03-30 17:18:18.120765,2025,3,30,17,18,18,Yes,Pending,NaN,CUS-WUQQU,Jorge Johnson,Male,47,Regular,Canada,Vancouver,50.50,50,2021-05-20,PRD-W4RY,Wireless Bluetooth Earbuds,Electronics,Tablets,JBL,4.70,1075,677,103.17,3,5,15.48,294.03,174.36,119.67,20.45,USD,Apple Pay,Paid,Yes,Next Day,16.19,4,Canada,Asia-Pacific,Delivered,5,Positive,Great product!,No,NaN,Facebook,Tablet,Social,26.50,5,No,39.00,40.70,High,Yes
999145,ORD-HCWCS,2024-08-12 12:06:38.671948,2024,8,12,12,6,38,No,Processing,NaN,CUS-G6I8U,Jerry Bender,Male,25,Premium,Netherlands,Amsterdam,90.60,18,2022-07-16,PRD-KIUC,Laptop Backpack Waterproof,Electronics,Tablets,Anker,3.50,3821,574,254.70,2,0,0.00,509.40,208.58,300.82,42.93,USD,PayPal,Paid,No,Express,14.67,12,Netherlands,Asia-Pacific,Delivered,1,Negative,Good value for money,No,NaN,Email,Desktop,Social,26.10,8,No,5.30,59.05,Medium,No
622125,ORD-N60M7,2024-07-11 19:25:12.112229,2024,7,11,19,25,12,No,Pending,NaN,CUS-97XRO,Suzanne Lopez,Female,26,Premium,United States,New York,70.40,35,2024-06-10,PRD-U268,Exercise Ball,Sports,Sports Wear,Nike,4.70,1936,910,202.55,5,15,151.91,860.84,497.20,363.64,50.68,USD,Debit Card,Pending,Yes,Express,2.61,2,United States,USA-West,Delivered,3,Neutral,NaN,No,NaN,Instagram,Tablet,Social,47.70,8,Yes,92.50,42.24,Low,Yes
876676,ORD-U3N5T,2024-02-15 08:42:20.129600,2024,2,15,8,42,20,No,Pending,NaN,CUS-0BL7B,Nancy Davis,Female,60,Premium,United States,New York,68.60,49,2023-06-30,PRD-UY0H,Vitamin C Tablets,Health,Medical Devices,Nike,4.30,3536,208,194.27,3,15,87.42,495.39,405.81,89.58,28.42,USD,Debit Card,Failed,Yes,Next Day,22.75,5,United States,UK,Delivered,1,Negative,NaN,No,NaN,Affiliate,Mobile,Direct,46.40,7,No,26.40,18.08,Medium,Yes

In [5]:
# Check the overall dataset dimensions: rows and columns.
ecommerce_df.shape

(1000123, 62)

In [6]:
# Print a concise summary of column types and non-null counts.
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 62 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  object
 1   order_date                1000123 non-null  object
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  object
 9   order_status              1000123 non-null  object
 10  return_reason             99879 non-null    object
 11  customer_id               1000123 non-null  object
 12  customer_name             1000123 non-null  object
 13  gender                    1000123 non-null  object
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  object
 16  country                   1000123 non-null  object
 17  city                      1000123 non-null  object
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  object
 21  product_id                1000123 non-null  object
 22  product_name              1000123 non-null  object
 23  category                  1000123 non-null  object
 24  sub_category              1000123 non-null  object
 25  brand                     1000123 non-null  object
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  object
 38  payment_method            1000123 non-null  object
 39  payment_status            1000123 non-null  object
 40  installment_plan          1000123 non-null  object
 41  shipping_method           1000123 non-null  object
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  object
 45  warehouse_location        1000123 non-null  object
 46  delivery_status           1000123 non-null  object
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  object
 49  customer_feedback         800506 non-null   object
 50  coupon_used               1000123 non-null  object
 51  coupon_code               500040 non-null   object
 52  campaign_source           1000123 non-null  object
 53  device_type               1000123 non-null  object
 54  traffic_source            1000123 non-null  object
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  object
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  object
 61  support_ticket_created    1000123 non-null  object
dtypes: float64(12), int64(15), object(35)
memory usage: 473.1+ MB

In [7]:
# Compute descriptive statistics
ecommerce_df.describe()

,order_year,order_month,order_day,order_hour,order_minute,order_second,age,customer_loyalty_score,total_orders_by_customer,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,shipping_cost_usd,delivery_days,rating,session_duration_minutes,pages_visited,fraud_risk_score,profit_margin_percent
count,"1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00"
mean,"2,024.59",6.51,15.75,11.49,29.49,29.49,46.49,49.97,25.49,4.00,"2,501.57",499.81,147.02,3.00,8.50,37.48,403.24,242.31,160.93,30.25,12.50,7.51,3.00,30.51,10.51,49.96,39.47
std,0.58,3.45,8.80,6.92,17.31,17.33,16.73,28.89,14.43,0.58,"1,443.46",288.86,103.67,1.41,7.60,56.78,370.13,226.72,161.93,28.89,7.22,4.03,1.41,17.03,5.77,28.85,10.94
min,"2,024.00",1.00,1.00,0.00,0.00,0.00,18.00,0.00,1.00,3.00,0.00,0.00,10.00,1.00,0.00,0.00,7.53,4.03,0.70,0.43,0.00,1.00,1.00,1.00,1.00,0.00,6.66
25%,"2,024.00",4.00,8.00,5.00,14.00,14.00,32.00,24.90,13.00,3.50,"1,253.00",250.00,69.51,2.00,0.00,0.00,139.02,82.45,50.69,10.12,6.26,4.00,2.00,15.70,6.00,25.00,31.69
50%,"2,025.00",7.00,16.00,11.00,30.00,29.00,46.00,50.00,25.00,4.00,"2,503.00",500.00,125.11,3.00,10.00,16.91,290.19,172.53,108.79,21.28,12.50,8.00,3.00,30.50,11.00,50.00,39.90
75%,"2,025.00",10.00,23.00,17.00,44.00,44.00,61.00,75.00,38.00,4.50,"3,752.00",750.00,195.61,4.00,15.00,49.26,545.76,326.45,214.64,40.59,18.74,11.00,4.00,45.30,16.00,74.90,48.17
max,"2,026.00",12.00,31.00,23.00,59.00,59.00,75.00,100.00,50.00,5.00,"5,000.00","1,000.00",500.00,5.00,25.00,624.71,"2,499.75","1,743.70","1,495.75",245.59,25.00,14.00,5.00,60.00,20.00,100.00,60.02

In [8]:
# Calculate and print the percentage of missing values per column.
print((ecommerce_df.isnull().sum() / ecommerce_df.shape[0] * 100).round(2).to_string())

order_id                    0.00
order_date                  0.00
order_year                  0.00
order_month                 0.00
order_day                   0.00
order_hour                  0.00
order_minute                0.00
order_second                0.00
is_weekend                  0.00
order_status                0.00
return_reason              90.01
customer_id                 0.00
customer_name               0.00
gender                      0.00
age                         0.00
customer_segment            0.00
country                     0.00
city                        0.00
customer_loyalty_score      0.00
total_orders_by_customer    0.00
account_creation_date       0.00
product_id                  0.00
product_name                0.00
category                    0.00
sub_category                0.00
brand                       0.00
product_rating_avg          0.00
product_reviews_count       0.00
stock_quantity              0.00
unit_price_usd              0.00
quantity                    0.00
discount_percent            0.00
discount_amount_usd         0.00
total_price_usd             0.00
cost_usd                    0.00
profit_usd                  0.00
tax_usd                     0.00
currency                    0.00
payment_method              0.00
payment_status              0.00
installment_plan            0.00
shipping_method             0.00
shipping_cost_usd           0.00
delivery_days               0.00
shipping_country            0.00
warehouse_location          0.00
delivery_status             0.00
rating                      0.00
review_sentiment            0.00
customer_feedback          19.96
coupon_used                 0.00
coupon_code                50.00
campaign_source             0.00
device_type                 0.00
traffic_source              0.00
session_duration_minutes    0.00
pages_visited               0.00
abandoned_cart_before       0.00
fraud_risk_score            0.00
profit_margin_percent       0.00
order_priority              0.00
support_ticket_created      0.00

Notable missing values were observed in **``return_season``**, **``customer_feedback``**, and **``coupon_code``**.

In [9]:
# Total of duplicate rows
duplicates_row = ecommerce_df.duplicated().sum()
print(f'Total of Duplicate Rows : {duplicates_row}')

Total of Duplicate Rows : 0

In [10]:
# Number of duplicate values per column
duplicates_per_col = ecommerce_df.apply(lambda col: col.duplicated().sum())
print(duplicates_per_col.to_string())

order_id                       8193
order_date                        0
order_year                  1000120
order_month                 1000111
order_day                   1000092
order_hour                  1000099
order_minute                1000063
order_second                1000063
is_weekend                  1000121
order_status                1000118
return_reason               1000117
customer_id                    8178
customer_name                669967
gender                      1000121
age                         1000065
customer_segment            1000120
country                     1000113
city                        1000073
customer_loyalty_score       999122
total_orders_by_customer    1000073
account_creation_date        998297
product_id                   246607
product_name                1000075
category                    1000118
sub_category                1000101
brand                       1000103
product_rating_avg          1000102
product_reviews_count        995122
stock_quantity               999122
unit_price_usd               951429
quantity                    1000118
discount_percent            1000117
discount_amount_usd          966868
total_price_usd              860597
cost_usd                     919136
profit_usd                   925125
tax_usd                      981106
currency                    1000122
payment_method              1000118
payment_status              1000120
installment_plan            1000121
shipping_method             1000119
shipping_cost_usd            997622
delivery_days               1000109
shipping_country            1000113
warehouse_location          1000118
delivery_status             1000119
rating                      1000118
review_sentiment            1000120
customer_feedback           1000114
coupon_used                 1000121
coupon_code                  953466
campaign_source             1000117
device_type                 1000120
traffic_source              1000118
session_duration_minutes     999532
pages_visited               1000103
abandoned_cart_before       1000121
fraud_risk_score             999122
profit_margin_percent        994786
order_priority              1000120
support_ticket_created      1000121

>Based on the data, it appears that the dataset does not have a unique identifier column.