# Data Understanding
This notebook loads the e-commerce dataset and inspects its structure, data types, summary statistics, missing values, and duplicate records.

In [16]:
# Load pandas for data manipulation.
import pandas as pd

# Set option to display all columns and format float values to two decimal places (to avoid scientific notation).
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)

In [17]:
# Read the raw e-commerce dataset from the project dataset folder.
ecommerce_df = pd.read_csv(r'dataset/raw/ecommerce_dataset_+1m.csv')

In [18]:
# DIsplay a random sample of 10 rows from the dataset to get an overview of the data.
ecommerce_df.sample(10)

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,return_reason,customer_id,customer_name,gender,age,customer_segment,country,city,customer_loyalty_score,total_orders_by_customer,account_creation_date,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,currency,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,rating,review_sentiment,customer_feedback,coupon_used,coupon_code,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
501720,ORD-U9I6Z,2024-09-11 00:16:55.038476,2024,9,11,0,16,55,No,Completed,NaN,CUS-QW9A4,Amanda Hayes,Female,41,Regular,Italy,Milan,6.10,42,2023-04-17,PRD-8Q7M,Wireless Mouse 2.4GHz,Electronics,Laptops,Apple,3.50,2498,612,27.51,3,0,0.00,82.53,46.41,36.12,4.91,USD,PayPal,Paid,No,Next Day,6.41,2,Italy,UK,In Transit,1,Negative,Highly recommended,No,NaN,Google Ads,Mobile,Direct,23.40,4,No,83.50,43.77,Medium,No
384708,ORD-JAM41,2025-06-26 10:53:53.804012,2025,6,26,10,53,53,No,Completed,NaN,CUS-XB35G,William Mason,Male,50,VIP,United States,New York,62.90,25,2022-08-24,PRD-FX50,Denim Jeans Slim Fit,Clothing,Shoes,Adidas,4.00,1217,761,28.18,3,0,0.00,84.54,47.13,37.41,4.34,USD,Credit Card,Paid,No,Next Day,24.08,3,United States,UK,In Transit,1,Negative,Great product!,No,NaN,Email,Desktop,Search,49.70,8,Yes,8.70,44.25,Low,No
578705,ORD-A6XCJ,2024-09-15 00:53:19.915484,2024,9,15,0,53,19,Yes,Returned,Changed Mind,CUS-90PK9,Elizabeth Vega,Female,46,Premium,Canada,Ottawa,2.70,1,2023-10-04,PRD-XGJX,Phone Case Shockproof,Electronics,Tablets,JBL,3.50,751,25,360.16,4,0,0.00,"1,440.64",740.44,700.20,124.42,USD,Bank Transfer,Paid,No,Standard,18.53,12,Canada,USA-East,Delivered,1,Negative,Fast delivery,No,NaN,Affiliate,Mobile,Email,20.60,19,Yes,45.60,48.60,High,Yes
367462,ORD-D60KZ,2024-10-18 17:15:52.063114,2024,10,18,17,15,52,No,Pending,NaN,CUS-YKN10,Brittany Weiss,Female,37,Premium,Australia,Melbourne,42.80,36,2024-01-10,PRD-89FX,Tennis Balls Pack,Sports,Outdoor,Nike,3.10,1927,381,114.07,5,0,0.00,570.35,328.65,241.70,56.15,USD,Credit Card,Pending,No,Economy,9.23,14,Australia,USA-West,Delivered,2,Negative,NaN,Yes,CPN-KDH,Google Ads,Desktop,Referral,35.60,1,Yes,0.40,42.38,High,Yes
73519,ORD-I6UQP,2025-12-29 20:24:22.552777,2025,12,29,20,24,22,No,Cancelled,NaN,CUS-O154K,Kristen Diaz DDS,Female,40,Premium,Belgium,Brussels,97.50,45,2022-01-16,PRD-CA2E,Portable SSD 1TB,Electronics,Audio,Logitech,4.10,4112,331,414.38,2,10,82.88,745.88,413.14,332.74,65.80,USD,PayPal,Paid,No,Express,20.84,9,Belgium,Asia-Pacific,Delivered,5,Positive,Highly recommended,No,NaN,Email,Mobile,Social,52.90,9,No,92.50,44.61,High,No
345424,ORD-V25RZ,2024-10-14 23:18:30.577879,2024,10,14,23,18,30,No,Cancelled,NaN,CUS-B0IP5,Jeffrey Fisher,Male,45,Regular,United States,Houston,94.70,34,2022-09-10,PRD-ZU3J,Smart Watch Series 8,Electronics,Laptops,GoPro,4.60,3365,686,286.43,4,0,0.00,"1,145.72",471.20,674.52,105.96,USD,Debit Card,Failed,No,Economy,16.34,7,United States,USA-West,Delivered,3,Neutral,Average quality,Yes,CPN-PD9,Instagram,Tablet,Referral,34.30,2,Yes,85.20,58.87,Medium,No
459325,ORD-Q8MX0,2024-09-05 00:16:45.702727,2024,9,5,0,16,45,No,Completed,NaN,CUS-RM7BJ,Sarah Taylor DVM,Female,52,Regular,Germany,Munich,80.50,42,2021-03-30,PRD-KPDD,Smart Watch Series 8,Electronics,Accessories,Nikon,4.30,607,237,452.91,5,0,0.00,"2,264.55","1,408.40",856.15,217.35,USD,PayPal,Paid,No,Economy,13.63,2,Germany,USA-East,In Transit,3,Neutral,Great product!,No,NaN,Google Ads,Desktop,Email,31.80,13,Yes,83.80,37.81,Low,No
440594,ORD-J9L65,2025-02-17 18:46:27.494433,2025,2,17,18,46,27,No,Completed,NaN,CUS-3QBI2,Monica Williams,Female,52,Regular,Australia,Perth,57.10,30,2021-12-20,PRD-8PU1,Baseball Cap,Clothing,Accessories,GoPro,3.30,4568,938,53.48,1,10,5.35,48.13,35.85,12.28,3.62,USD,Apple Pay,Paid,No,Next Day,6.53,6,Australia,USA-East,Delivered,3,Neutral,Good value for money,No,NaN,Email,Desktop,Direct,14.40,7,No,35.70,25.51,High,No
916415,ORD-T1H5O,2025-09-10 09:07:04.283500,2025,9,10,9,7,4,No,Completed,NaN,CUS-U93DQ,Gary Thomas,Male,31,Regular,Spain,Barcelona,96.30,38,2024-02-23,PRD-1YAF,USB Hub 7-Port,Electronics,Accessories,Nike,3.70,4199,679,243.11,4,0,0.00,972.44,534.72,437.72,51.55,USD,Apple Pay,Paid,Yes,Economy,5.50,10,Spain,Asia-Pacific,Delivered,1,Negative,NaN,No,NaN,Email,Mobile,Social,28.10,7,No,14.80,45.01,Medium,Yes
484335,ORD-CJEQ8,2025-05-25 02:21:16.686243,2025,5,25,2,21,16,Yes,Completed,NaN,CUS-CM7AB,Shelby Banks,Female,21,Regular,France,Paris,4.40,21,2025-05-14,PRD-72YD,Gaming Mechanical Keyboard RGB,Electronics,Smartphones,Philips,3.70,1576,406,114.73,2,10,22.95,206.51,131.18,75.33,13.90,USD,Credit Card,Paid,Yes,Standard,8.68,2,France,EU-Central,Delivered,5,Positive,NaN,Yes,CPN-HVN,Affiliate,Tablet,Direct,21.20,11,No,38.90,36.48,Low,No

In [19]:
# Check the overall dataset dimensions: rows and columns.
ecommerce_df.shape

(1000123, 62)

In [20]:
# Print a concise summary of column types and non-null counts.
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 62 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  object
 1   order_date                1000123 non-null  object
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  object
 9   order_status              1000123 non-null  object
 10  return_reason             99879 non-null    object
 11  customer_id               1000123 non-null  object
 12  customer_name             1000123 non-null  object
 13  gender                    1000123 non-null  object
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  object
 16  country                   1000123 non-null  object
 17  city                      1000123 non-null  object
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  object
 21  product_id                1000123 non-null  object
 22  product_name              1000123 non-null  object
 23  category                  1000123 non-null  object
 24  sub_category              1000123 non-null  object
 25  brand                     1000123 non-null  object
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  object
 38  payment_method            1000123 non-null  object
 39  payment_status            1000123 non-null  object
 40  installment_plan          1000123 non-null  object
 41  shipping_method           1000123 non-null  object
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  object
 45  warehouse_location        1000123 non-null  object
 46  delivery_status           1000123 non-null  object
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  object
 49  customer_feedback         800506 non-null   object
 50  coupon_used               1000123 non-null  object
 51  coupon_code               500040 non-null   object
 52  campaign_source           1000123 non-null  object
 53  device_type               1000123 non-null  object
 54  traffic_source            1000123 non-null  object
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  object
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  object
 61  support_ticket_created    1000123 non-null  object
dtypes: float64(12), int64(15), object(35)
memory usage: 473.1+ MB

In [21]:
# Compute descriptive statistics
ecommerce_df.describe()

,order_year,order_month,order_day,order_hour,order_minute,order_second,age,customer_loyalty_score,total_orders_by_customer,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,shipping_cost_usd,delivery_days,rating,session_duration_minutes,pages_visited,fraud_risk_score,profit_margin_percent
count,"1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00"
mean,"2,024.59",6.51,15.75,11.49,29.49,29.49,46.49,49.97,25.49,4.00,"2,501.57",499.81,147.02,3.00,8.50,37.48,403.24,242.31,160.93,30.25,12.50,7.51,3.00,30.51,10.51,49.96,39.47
std,0.58,3.45,8.80,6.92,17.31,17.33,16.73,28.89,14.43,0.58,"1,443.46",288.86,103.67,1.41,7.60,56.78,370.13,226.72,161.93,28.89,7.22,4.03,1.41,17.03,5.77,28.85,10.94
min,"2,024.00",1.00,1.00,0.00,0.00,0.00,18.00,0.00,1.00,3.00,0.00,0.00,10.00,1.00,0.00,0.00,7.53,4.03,0.70,0.43,0.00,1.00,1.00,1.00,1.00,0.00,6.66
25%,"2,024.00",4.00,8.00,5.00,14.00,14.00,32.00,24.90,13.00,3.50,"1,253.00",250.00,69.51,2.00,0.00,0.00,139.02,82.45,50.69,10.12,6.26,4.00,2.00,15.70,6.00,25.00,31.69
50%,"2,025.00",7.00,16.00,11.00,30.00,29.00,46.00,50.00,25.00,4.00,"2,503.00",500.00,125.11,3.00,10.00,16.91,290.19,172.53,108.79,21.28,12.50,8.00,3.00,30.50,11.00,50.00,39.90
75%,"2,025.00",10.00,23.00,17.00,44.00,44.00,61.00,75.00,38.00,4.50,"3,752.00",750.00,195.61,4.00,15.00,49.26,545.76,326.45,214.64,40.59,18.74,11.00,4.00,45.30,16.00,74.90,48.17
max,"2,026.00",12.00,31.00,23.00,59.00,59.00,75.00,100.00,50.00,5.00,"5,000.00","1,000.00",500.00,5.00,25.00,624.71,"2,499.75","1,743.70","1,495.75",245.59,25.00,14.00,5.00,60.00,20.00,100.00,60.02

In [22]:
# Calculate and print the percentage of missing values per column.
print((ecommerce_df.isnull().sum() / ecommerce_df.shape[0] * 100).round(2).to_string())

order_id                    0.00
order_date                  0.00
order_year                  0.00
order_month                 0.00
order_day                   0.00
order_hour                  0.00
order_minute                0.00
order_second                0.00
is_weekend                  0.00
order_status                0.00
return_reason              90.01
customer_id                 0.00
customer_name               0.00
gender                      0.00
age                         0.00
customer_segment            0.00
country                     0.00
city                        0.00
customer_loyalty_score      0.00
total_orders_by_customer    0.00
account_creation_date       0.00
product_id                  0.00
product_name                0.00
category                    0.00
sub_category                0.00
brand                       0.00
product_rating_avg          0.00
product_reviews_count       0.00
stock_quantity              0.00
unit_price_usd              0.00
quantity                    0.00
discount_percent            0.00
discount_amount_usd         0.00
total_price_usd             0.00
cost_usd                    0.00
profit_usd                  0.00
tax_usd                     0.00
currency                    0.00
payment_method              0.00
payment_status              0.00
installment_plan            0.00
shipping_method             0.00
shipping_cost_usd           0.00
delivery_days               0.00
shipping_country            0.00
warehouse_location          0.00
delivery_status             0.00
rating                      0.00
review_sentiment            0.00
customer_feedback          19.96
coupon_used                 0.00
coupon_code                50.00
campaign_source             0.00
device_type                 0.00
traffic_source              0.00
session_duration_minutes    0.00
pages_visited               0.00
abandoned_cart_before       0.00
fraud_risk_score            0.00
profit_margin_percent       0.00
order_priority              0.00
support_ticket_created      0.00

Notable missing values were observed in **``return_season``**, **``customer_feedback``**, and **``coupon_code``**.

In [23]:
# Total of duplicate rows
duplicates_row = ecommerce_df.duplicated().sum()
print(f'Total of Duplicate Rows : {duplicates_row}')

Total of Duplicate Rows : 0

In [24]:
# True = unique identifier candidate
print(ecommerce_df.apply(lambda col: col.is_unique).to_string())

order_id                    False
order_date                   True
order_year                  False
order_month                 False
order_day                   False
order_hour                  False
order_minute                False
order_second                False
is_weekend                  False
order_status                False
return_reason               False
customer_id                 False
customer_name               False
gender                      False
age                         False
customer_segment            False
country                     False
city                        False
customer_loyalty_score      False
total_orders_by_customer    False
account_creation_date       False
product_id                  False
product_name                False
category                    False
sub_category                False
brand                       False
product_rating_avg          False
product_reviews_count       False
stock_quantity              False
unit_price_usd              False
quantity                    False
discount_percent            False
discount_amount_usd         False
total_price_usd             False
cost_usd                    False
profit_usd                  False
tax_usd                     False
currency                    False
payment_method              False
payment_status              False
installment_plan            False
shipping_method             False
shipping_cost_usd           False
delivery_days               False
shipping_country            False
warehouse_location          False
delivery_status             False
rating                      False
review_sentiment            False
customer_feedback           False
coupon_used                 False
coupon_code                 False
campaign_source             False
device_type                 False
traffic_source              False
session_duration_minutes    False
pages_visited               False
abandoned_cart_before       False
fraud_risk_score            False
profit_margin_percent       False
order_priority              False
support_ticket_created      False

>Based on the data, it appears that the dataset does not have a suitable unique identifier column. Although order_date contains unique values, it is not a reliable unique identifier since it is a timestamp and may not remain unique in real-world scenarios.