# Data Understanding
This notebook loads the e-commerce dataset and inspects its structure, data types, summary statistics, missing values, and duplicate records.

In [25]:
# Load pandas for data manipulation.
import pandas as pd

# Set option to display all columns and format float values to two decimal places (to avoid scientific notation).
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)

In [26]:
# Read the raw e-commerce dataset from the project dataset folder.
ecommerce_df = pd.read_csv(r'dataset/raw/ecommerce_dataset_+1m.csv')

In [27]:
# DIsplay a random sample of 10 rows from the dataset to get an overview of the data.
ecommerce_df.sample(10)

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,return_reason,customer_id,customer_name,gender,age,customer_segment,country,city,customer_loyalty_score,total_orders_by_customer,account_creation_date,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,currency,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,rating,review_sentiment,customer_feedback,coupon_used,coupon_code,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
909053,ORD-M1NXZ,2025-06-25 20:15:19.175524,2025,6,25,20,15,19,No,Pending,NaN,CUS-GZHEW,Barbara Ortega,Female,57,Premium,France,Marseille,32.40,17,2021-08-20,PRD-ZDLD,Sports Bra High Impact,Clothing,Shoes,GoPro,3.60,1514,886,59.46,3,10,17.84,160.54,104.94,55.60,15.29,USD,PayPal,Pending,Yes,Express,21.47,1,France,USA-West,Delivered,5,Positive,Not satisfied,Yes,CPN-AUT,Organic,Desktop,Social,13.30,12,No,95.90,34.63,High,Yes
217705,ORD-4GEOB,2024-02-22 18:22:46.869696,2024,2,22,18,22,46,No,Completed,NaN,CUS-OXDW6,Benjamin Mora,Male,23,Regular,Germany,Berlin,99.30,19,2021-04-18,PRD-0XKJ,Exercise Ball,Sports,Outdoor,Apple,4.70,449,215,177.97,5,5,44.49,845.36,481.40,363.96,44.71,USD,Bank Transfer,Paid,Yes,Standard,12.32,6,Germany,Asia-Pacific,Delivered,4,Positive,Good value for money,Yes,CPN-Q0W,Instagram,Tablet,Direct,45.30,10,Yes,39.80,43.05,Medium,No
895495,ORD-938AS,2024-07-24 23:09:41.428583,2024,7,24,23,9,41,No,Completed,NaN,CUS-XQ35G,Ryan Fox,Male,51,VIP,Canada,Ottawa,18.10,9,2024-02-18,PRD-1XXE,Resistance Bands Set,Health,Medical Devices,Baseus,4.10,3289,674,189.29,5,10,94.64,851.81,590.35,261.46,70.59,USD,Debit Card,Paid,No,Express,13.45,5,Canada,USA-West,In Transit,5,Positive,NaN,Yes,CPN-IWZ,Facebook,Tablet,Referral,42.10,8,No,32.00,30.69,Low,Yes
198574,ORD-ELFRD,2026-01-20 23:45:30.614302,2026,1,20,23,45,30,No,Completed,NaN,CUS-X5T73,Christopher Mora,Male,55,Regular,United States,New York,68.90,37,2021-09-26,PRD-H4XP,Digital Blood Pressure Monitor,Health,Supplements,Apple,4.00,3012,842,56.83,3,15,25.57,144.92,104.58,40.34,10.47,USD,Apple Pay,Paid,No,Economy,16.20,14,United States,EU-Central,Failed,5,Positive,NaN,No,NaN,Organic,Tablet,Direct,25.00,20,Yes,20.90,27.84,Low,No
524922,ORD-4NOPF,2024-11-09 18:41:32.590102,2024,11,9,18,41,32,Yes,Completed,NaN,CUS-TIDEY,Dorothy Santos,Female,67,Premium,United States,Phoenix,37.60,11,2023-06-08,PRD-9ZQL,Jump Rope Speed,Sports,Sports Wear,Sony,4.00,611,986,117.20,1,20,23.44,93.76,73.46,20.30,7.68,USD,Debit Card,Paid,No,Standard,24.15,3,United States,UK,In Transit,1,Negative,Average quality,Yes,CPN-DTC,Facebook,Desktop,Referral,13.50,4,No,47.50,21.65,High,No
539439,ORD-XJ098,2025-08-12 16:05:21.079761,2025,8,12,16,5,21,No,Pending,NaN,CUS-I1MW4,Mary Sanders,Female,64,Regular,Canada,Ottawa,68.40,8,2025-04-23,PRD-CHYQ,Massage Gun Deep Tissue,Health,Personal Care,JBL,4.30,1037,32,28.21,3,25,21.16,63.47,34.08,29.39,6.28,USD,PayPal,Paid,No,Next Day,1.44,8,Canada,UK,Pending,1,Negative,Could be better,No,NaN,Facebook,Desktop,Search,18.70,15,No,31.10,46.31,High,Yes
480288,ORD-W3VI6,2025-05-19 16:29:55.315025,2025,5,19,16,29,55,No,Completed,NaN,CUS-2NAPN,Christine Williams,Female,59,Regular,Germany,Hamburg,20.70,39,2024-08-06,PRD-FVJM,Coffee Maker Automatic,Home,Furniture,Baseus,4.40,2972,754,274.00,2,0,0.00,548.00,345.22,202.78,41.35,USD,Apple Pay,Paid,Yes,Next Day,20.02,8,Germany,Asia-Pacific,Pending,1,Negative,Could be better,Yes,CPN-HFJ,Instagram,Tablet,Email,52.00,17,No,96.00,37.00,Low,No
395212,ORD-H4INF,2024-09-07 15:01:40.418154,2024,9,7,15,1,40,Yes,Pending,NaN,CUS-ES5JV,Barbara Gray,Female,64,Regular,Canada,Ottawa,25.20,40,2024-08-31,PRD-4LFW,Vitamin C Tablets,Health,Supplements,Fitbit,4.00,3515,198,110.79,1,0,0.00,110.79,64.43,46.36,5.93,USD,Bank Transfer,Pending,Yes,Express,11.31,2,Canada,Asia-Pacific,Delivered,2,Negative,NaN,Yes,CPN-AOP,Email,Mobile,Referral,30.30,10,No,9.70,41.84,Medium,Yes
561883,ORD-9OSXI,2025-06-08 20:22:14.894476,2025,6,8,20,22,14,Yes,Completed,NaN,CUS-EAB8S,Nicole Spears,Female,21,Premium,Australia,Perth,62.30,13,2021-10-28,PRD-3MXY,Gaming Mechanical Keyboard RGB,Electronics,Laptops,Xiaomi,4.10,573,702,181.38,1,10,18.14,163.24,95.04,68.20,13.12,USD,Bank Transfer,Paid,No,Express,18.56,8,Australia,USA-West,Delivered,3,Neutral,NaN,Yes,CPN-KZQ,Facebook,Desktop,Direct,1.80,15,No,27.80,41.78,Medium,Yes
660408,ORD-O8TFV,2025-05-18 04:10:45.752976,2025,5,18,4,10,45,Yes,Pending,NaN,CUS-3K9P8,Ashley Reyes,Female,63,Premium,Germany,Berlin,62.90,29,2023-02-09,PRD-2UPG,Resistance Bands Set,Health,Personal Care,Samsung,4.80,1452,740,90.96,2,5,9.10,172.82,96.88,75.94,16.22,USD,Apple Pay,Paid,Yes,Next Day,18.60,6,Germany,Asia-Pacific,Delivered,5,Positive,Fast delivery,Yes,CPN-851,Email,Desktop,Search,22.80,4,Yes,55.40,43.94,High,No

In [28]:
# Check the overall dataset dimensions: rows and columns.
ecommerce_df.shape

(1000123, 62)

In [29]:
# Print a concise summary of column types and non-null counts.
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 62 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  object
 1   order_date                1000123 non-null  object
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  object
 9   order_status              1000123 non-null  object
 10  return_reason             99879 non-null    object
 11  customer_id               1000123 non-null  object
 12  customer_name             1000123 non-null  object
 13  gender                    1000123 non-null  object
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  object
 16  country                   1000123 non-null  object
 17  city                      1000123 non-null  object
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  object
 21  product_id                1000123 non-null  object
 22  product_name              1000123 non-null  object
 23  category                  1000123 non-null  object
 24  sub_category              1000123 non-null  object
 25  brand                     1000123 non-null  object
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  object
 38  payment_method            1000123 non-null  object
 39  payment_status            1000123 non-null  object
 40  installment_plan          1000123 non-null  object
 41  shipping_method           1000123 non-null  object
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  object
 45  warehouse_location        1000123 non-null  object
 46  delivery_status           1000123 non-null  object
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  object
 49  customer_feedback         800506 non-null   object
 50  coupon_used               1000123 non-null  object
 51  coupon_code               500040 non-null   object
 52  campaign_source           1000123 non-null  object
 53  device_type               1000123 non-null  object
 54  traffic_source            1000123 non-null  object
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  object
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  object
 61  support_ticket_created    1000123 non-null  object
dtypes: float64(12), int64(15), object(35)
memory usage: 473.1+ MB

In [30]:
# Compute descriptive statistics
ecommerce_df.describe()

,order_year,order_month,order_day,order_hour,order_minute,order_second,age,customer_loyalty_score,total_orders_by_customer,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,quantity,discount_percent,discount_amount_usd,total_price_usd,cost_usd,profit_usd,tax_usd,shipping_cost_usd,delivery_days,rating,session_duration_minutes,pages_visited,fraud_risk_score,profit_margin_percent
count,"1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00","1,000,123.00"
mean,"2,024.59",6.51,15.75,11.49,29.49,29.49,46.49,49.97,25.49,4.00,"2,501.57",499.81,147.02,3.00,8.50,37.48,403.24,242.31,160.93,30.25,12.50,7.51,3.00,30.51,10.51,49.96,39.47
std,0.58,3.45,8.80,6.92,17.31,17.33,16.73,28.89,14.43,0.58,"1,443.46",288.86,103.67,1.41,7.60,56.78,370.13,226.72,161.93,28.89,7.22,4.03,1.41,17.03,5.77,28.85,10.94
min,"2,024.00",1.00,1.00,0.00,0.00,0.00,18.00,0.00,1.00,3.00,0.00,0.00,10.00,1.00,0.00,0.00,7.53,4.03,0.70,0.43,0.00,1.00,1.00,1.00,1.00,0.00,6.66
25%,"2,024.00",4.00,8.00,5.00,14.00,14.00,32.00,24.90,13.00,3.50,"1,253.00",250.00,69.51,2.00,0.00,0.00,139.02,82.45,50.69,10.12,6.26,4.00,2.00,15.70,6.00,25.00,31.69
50%,"2,025.00",7.00,16.00,11.00,30.00,29.00,46.00,50.00,25.00,4.00,"2,503.00",500.00,125.11,3.00,10.00,16.91,290.19,172.53,108.79,21.28,12.50,8.00,3.00,30.50,11.00,50.00,39.90
75%,"2,025.00",10.00,23.00,17.00,44.00,44.00,61.00,75.00,38.00,4.50,"3,752.00",750.00,195.61,4.00,15.00,49.26,545.76,326.45,214.64,40.59,18.74,11.00,4.00,45.30,16.00,74.90,48.17
max,"2,026.00",12.00,31.00,23.00,59.00,59.00,75.00,100.00,50.00,5.00,"5,000.00","1,000.00",500.00,5.00,25.00,624.71,"2,499.75","1,743.70","1,495.75",245.59,25.00,14.00,5.00,60.00,20.00,100.00,60.02

In [31]:
# Get the percentage of missing values for each column in the dataset.
print((ecommerce_df.isnull().sum() / ecommerce_df.shape[0] * 100).round(2).to_string())

order_id                    0.00
order_date                  0.00
order_year                  0.00
order_month                 0.00
order_day                   0.00
order_hour                  0.00
order_minute                0.00
order_second                0.00
is_weekend                  0.00
order_status                0.00
return_reason              90.01
customer_id                 0.00
customer_name               0.00
gender                      0.00
age                         0.00
customer_segment            0.00
country                     0.00
city                        0.00
customer_loyalty_score      0.00
total_orders_by_customer    0.00
account_creation_date       0.00
product_id                  0.00
product_name                0.00
category                    0.00
sub_category                0.00
brand                       0.00
product_rating_avg          0.00
product_reviews_count       0.00
stock_quantity              0.00
unit_price_usd              0.00
quantity                    0.00
discount_percent            0.00
discount_amount_usd         0.00
total_price_usd             0.00
cost_usd                    0.00
profit_usd                  0.00
tax_usd                     0.00
currency                    0.00
payment_method              0.00
payment_status              0.00
installment_plan            0.00
shipping_method             0.00
shipping_cost_usd           0.00
delivery_days               0.00
shipping_country            0.00
warehouse_location          0.00
delivery_status             0.00
rating                      0.00
review_sentiment            0.00
customer_feedback          19.96
coupon_used                 0.00
coupon_code                50.00
campaign_source             0.00
device_type                 0.00
traffic_source              0.00
session_duration_minutes    0.00
pages_visited               0.00
abandoned_cart_before       0.00
fraud_risk_score            0.00
profit_margin_percent       0.00
order_priority              0.00
support_ticket_created      0.00

Notable missing values were observed in **``return_season``**, **``customer_feedback``**, and **``coupon_code``**.

In [32]:
# Total of duplicate rows
duplicates_row = ecommerce_df.duplicated().sum()
print(f'Total of Duplicate Rows : {duplicates_row}')

Total of Duplicate Rows : 0

In [33]:
"""
    Determine if any column in the dataset has unique values, which can be used as a unique identifier for each row. 
    True = unique identifier candidate
"""
print(ecommerce_df.apply(lambda col: col.is_unique).to_string())

order_id                    False
order_date                   True
order_year                  False
order_month                 False
order_day                   False
order_hour                  False
order_minute                False
order_second                False
is_weekend                  False
order_status                False
return_reason               False
customer_id                 False
customer_name               False
gender                      False
age                         False
customer_segment            False
country                     False
city                        False
customer_loyalty_score      False
total_orders_by_customer    False
account_creation_date       False
product_id                  False
product_name                False
category                    False
sub_category                False
brand                       False
product_rating_avg          False
product_reviews_count       False
stock_quantity              False
unit_price_usd              False
quantity                    False
discount_percent            False
discount_amount_usd         False
total_price_usd             False
cost_usd                    False
profit_usd                  False
tax_usd                     False
currency                    False
payment_method              False
payment_status              False
installment_plan            False
shipping_method             False
shipping_cost_usd           False
delivery_days               False
shipping_country            False
warehouse_location          False
delivery_status             False
rating                      False
review_sentiment            False
customer_feedback           False
coupon_used                 False
coupon_code                 False
campaign_source             False
device_type                 False
traffic_source              False
session_duration_minutes    False
pages_visited               False
abandoned_cart_before       False
fraud_risk_score            False
profit_margin_percent       False
order_priority              False
support_ticket_created      False

>Based on the data, it appears that the dataset does not have a suitable unique identifier column. Although order_date contains unique values, it is not a reliable unique identifier since it is a timestamp and may not remain unique in real-world scenarios.